### ISSUE TITLE
Designe en UI til login i AdobeXD

### ISSUE THREAD

**Issue by NikoThor** [BenjaminKyhn/Zealand-Connect-Team-Cyclone#2]
[Login.UI.pdf](https://github.com/BenjaminKyhn/Zealand-Connect-Team-Cyclone/files/5439262/Login.UI.pdf)

**Comment by Kelvin-EASJ** [comment]
[Login UI.pdf](https://github.com/BenjaminKyhn/Zealand-Connect-Team-Cyclone/files/5438942/Login.UI.pdf)

PDF file af Login UI fra Adobe XD

**Comment by BilleLind** [comment]
needed a page

**Comment by Kelvin-EASJ** [comment]
[Login UI.pdf](https://github.com/BenjaminKyhn/Zealand-Connect-Team-Cyclone/files/5439158/Login.UI.pdf)

**Comment by BilleLind** [comment]
Kevin "glemte at lukke døren efter ham"
